src/api/admin.py, src/api/routes.py
=> Log and db users

src/api/routes.py, src/front/js/pages/SignUp.jsx, src/front/js/store/flux.js
=> Signup fixed

migrations/versions/df32008da2f7_.py, src/api/models.py, src/front/js/component/CardsReview.js, src/front/js/component/ReviewCard.jsx, src/front/js/layout.js, src/front/js/pages/Reviews.js, src/front/js/pages/SignUp.jsx, src/front/js/pages/home.js, src/front/js/store/flux.js
REview get in flux, reviewscard modified
=> reviewscard, testing

migrations/versions/e1e7bdbe09b7_.py, src/api/routes.py, src/front/js/component/BusinessOfferCard.jsx, src/front/js/component/OfferCard.jsx, src/front/js/component/ReviewCard.jsx, src/front/js/store/flux.js
Fix offers submit feat OfferCard
merge to have final changes
=> Fix offers submit feat OfferCard

src/front/js/component/CardsReview.js, src/front/js/store/flux.js
=> update and delete reviews OK

src/front/js/pages/UserPrivate.jsx
update user profile building...
=> update profile user

src/front/js/component/CardsReview.js, src/front/js/component/ContactForm.js, src/front/js/component/FilterMenu.js, src/front/js/component/FormReview.js, src/front/js/component/HomeReviewCard.jsx, src/front/js/component/Navbar.jsx, src/front/js/component/SearchReview.js, src/front/js/component/UpdateProfileUser.js, src/front/js/pages/Reviews.js, src/front/js/pages/UserPrivate.jsx, src/front/js/store/flux.js, src/front/styles/card-review.css, src/front/styles/filter-menu.css, src/front/styles/form-review.css, src/front/styles/homeOfferCard.css, src/front/styles/index.css, src/front/styles/search-review.css
=> searchbar reviews OK

.vscode/settings.json, src/front/js/component/Navbar.jsx, src/front/js/pages/ForgotPassword.jsx, src/front/js/pages/home.js, src/front/styles/forgotPassword.css, src/front/styles/index.css
feat forgot_password_page_&_redirects_functions
=> feat forgot_password_page_&_redirects_functions

package-lock.json, package.json, src/api/routes.py, src/front/js/component/CardsReview.js, src/front/js/component/GooglePay.js, src/front/js/component/Navbar.jsx, src/front/js/component/PubSlide.js, src/front/js/component/UpdateProfileUser.js, src/front/js/pages/UserPrivate.jsx, src/front/js/store/flux.js, src/front/styles/homeReviewCard.css, src/front/styles/pub-slide.css, src/front/styles/signup.css
google pay OK, business_user OK
=> Feat pay and update

src/front/js/component/BusinessOfferCard.jsx, src/front/js/component/CardsReview.js, src/front/js/component/FormOffers.jsx, src/front/js/pages/Business_offers.jsx, src/front/styles/businessOfferCard.css, src/front/styles/card-review.css
cambios estilos + searchBar vista Offers and update form offer
=> cambios estilos + searchBar vista Offers and update form offer

src/api/models.py, src/api/routes.py, src/front/js/component/BusinessOfferCard.jsx, src/front/js/component/GooglePay.js, src/front/js/store/flux.js, src/front/styles/businessOfferCard.css, src/front/styles/card-review.css
Like in developemt - style fixed
=> Like in developemt - style fixed

.env.example, migrations/versions/7ef808d86b87_.py, src/api/routes.py, src/front/js/component/BusinessOfferCard.jsx, src/front/js/component/CardsReview.js, src/front/js/component/FormOffers.jsx, src/front/js/component/FormReview.js, src/front/js/component/HomeOfferCard.jsx, src/front/js/component/HomeReviewCard.jsx, src/front/js/pages/Business_offers.jsx, src/front/styles/homeOfferCard.css, src/front/styles/homeReviewCard.css
feat admin user, forms, and delete and update for offers
=> feat admin user, forms, and delete and update for offers

.env.example, .gitignore, migrations/versions/1d181c1aaa57_.py, src/front/js/component/HomeOfferCard.jsx, src/front/js/component/Likes.js
=> fixed code

src/front/js/layout.js, template.html
=> new commit paypal

src/api/models.py, src/api/routes.py, src/front/js/component/FormOffers.jsx, src/front/js/component/FormReview.js, src/front/js/component/LogIn.jsx, src/front/js/component/Navbar.jsx, src/front/js/component/OffersDoubleModal.jsx, src/front/js/component/PaymentOptions.js, src/front/js/component/ReviewsDoubleModal.jsx, src/front/js/component/SignUpBusiness.js, src/front/js/component/SignUpUser.jsx, src/front/js/layout.js, src/front/js/pages/Business_offers.jsx, src/front/js/pages/Reviews.js, src/front/js/pages/SingleOfferView.jsx, src/front/js/pages/SingleReviewView.jsx
Individual views new form double view
Feat modals with double view work like form in offer and view
and password auth and viewbutton
=> Feat modals with double view work like form in offer and view

server/index.js, server/package-lock.json, server/package.json, server/paypal-api.js
=> donation paypal

.env.example, src/api/models.py, src/api/routes.py, src/front/js/component/AllFavoritesOffers.js, src/front/js/component/AllFavoritesReviews.js, src/front/js/component/BusinessOfferCard.jsx, src/front/js/component/FavoriteOffer.jsx, src/front/js/component/MenuOffers.jsx, src/front/js/component/MyOffers.jsx, src/front/js/hooks/useOfferManagement.js, src/front/js/pages/Business_offers.jsx, src/front/js/pages/SingleReviewView.jsx, src/front/js/store/flux.js
=> Feat favorites 4 offers

src/api/models.py, src/api/paypal-api.py, src/api/routes.py, src/front/js/component/AllFavoritesOffers.js, src/front/js/component/BusinessOfferCard.jsx, src/front/js/component/PaymentComponent.js, src/front/js/component/PaymentOptions.js, src/front/js/hooks/useOfferManagement.js, src/front/js/hooks/useReviewManagement.js, src/front/js/layout.js, src/front/js/pages/SingleOfferView.jsx, src/front/js/store/flux.js, src/front/styles/payment.css
=> Paypal api

src/api/models.py, src/api/routes.py, src/front/js/component/AllFavoritesReviews.js, src/front/js/component/MenuReviews.js, src/front/js/component/MyReviews.js, src/front/js/component/SignUpBusiness.js, src/front/js/component/SignUpUser.jsx, src/front/js/pages/BusinessUserPrivate.jsx, src/front/js/pages/UserPrivate.jsx, src/front/styles/signup.css
Fix forms & signup login issues & photos for reviews
=> Fix forms & signup login issues

src/api/models.py, src/front/js/component/AllFavoritesOffers.js, src/front/js/component/AllFavoritesReviews.js, src/front/js/component/FavoriteOffer.jsx, src/front/js/component/FavoriteReview.js, src/front/js/store/flux.js
all favorites add and delete OK !!!!!!!!!!!!!!!! por fin!!!!!!!1
=> all favorites add and delete OK

src/front/js/component/ForgotPasswordForm.jsx, src/front/js/component/Navbar.jsx, src/front/js/component/SignUpBusiness.js, src/front/js/component/SignUpUser.jsx, src/front/styles/forgotPasswordForm.css, src/front/styles/signup.css
Styles 4 signup forms ok and passwordform 2 formik
=> Feat styles 4 _signup forms ok and passwordform 2 formik

src/front/js/component/DonationForm.js, src/front/js/component/FilterMenu.js, src/front/js/component/Footer.jsx, src/front/js/component/HomeOfferCard.jsx, src/front/js/component/LitlleSlide.jsx, src/front/js/component/Navbar.jsx, src/front/js/component/PubSlide.js, src/front/js/layout.js, src/front/js/pages/home.js, src/front/styles/filter-menu.css, src/front/styles/footer.css, src/front/styles/home.css, src/front/styles/homeOfferCard.css, src/front/styles/homeReviewCard.css, src/front/styles/litlleSlide.css, src/front/styles/navbar.css, src/front/styles/payment.css, src/front/styles/pub-slide.css, src/front/styles/search-review.css
=> responsive home

Pipfile, Pipfile.lock, src/api/routes.py, src/front/js/component/AdminBusiness.js, src/front/js/component/AdminOffers.js, src/front/js/component/AdminReviews.js, src/front/js/component/AdminUsers.js, src/front/js/component/BusinessOfferCard.jsx, src/front/js/component/CardsReview.js, src/front/js/component/Footer.jsx, src/front/js/component/Navbar.jsx, src/front/js/component/OffersDoubleModal.jsx, src/front/js/component/ReviewsDoubleModal.jsx, src/front/js/layout.js, src/front/js/pages/AdminView.js, src/front/js/pages/UserPrivate.jsx, src/front/js/pages/home.js, src/front/js/store/flux.js, src/front/styles/admin.css, src/front/styles/footer.css, src/front/styles/generalInfoDiv.css, src/front/styles/index.css, webpack.common.js
=> view admin and delete all OK

src/api/models.py, src/api/routes.py, src/front/js/component/AllFavoritesOffers.js, src/front/js/component/AllFavoritesReviews.js, src/front/js/component/BusinessOfferCard.jsx, src/front/js/component/CardsReview.js, src/front/js/component/Footer.jsx, src/front/js/component/MyOffers.jsx, src/front/js/component/MyReviews.js, src/front/js/component/Navbar.jsx, src/front/js/component/OffersDoubleModal.jsx, src/front/js/component/ReviewsDoubleModal.jsx, src/front/js/pages/LogIn.jsx, src/front/js/pages/SingleOfferView.jsx, src/front/js/pages/home.js, src/front/js/store/flux.js, src/front/styles/generalInfoDiv.css, src/front/styles/index.css, src/front/styles/navbar.css, src/front/styles/singleOfferView.css
Feat styles, select with countries, some little stuff
=> Feat styles, select with countries, some little stuff

src/front/js/component/AdminBusiness.js, src/front/js/component/AdminOffers.js, src/front/js/component/AdminReviews.js, src/front/js/component/AdminUsers.js, src/front/js/component/AllFavoritesOffers.js, src/front/js/component/AllFavoritesReviews.js, src/front/js/component/BusinessOfferCard.jsx, src/front/js/component/CardsReview.js, src/front/js/component/FavoriteReview.js, src/front/js/component/HomeReviewCard.jsx, src/front/js/component/MyReviews.js, src/front/js/component/OffersDoubleModal.jsx, src/front/js/component/SearchReview.js, src/front/js/pages/home.js, src/front/styles/admin.css, src/front/styles/card-review.css, src/front/styles/generalInfoDiv.css, src/front/styles/homeReviewCard.css, src/front/styles/index.css, src/front/styles/navbar.css, src/front/styles/search-review.css
=> Styles sprint

src/front/js/component/AllFavoritesReviews.js, src/front/js/component/CardsReview.js, src/front/js/component/FavoriteReview.js, src/front/js/component/HomeReviewCard.jsx, src/front/js/component/MyReviews.js, src/front/js/pages/Favorites.js, src/front/styles/card-review.css, src/front/styles/homeReviewCard.css
=> reviews styles all views OK

src/api/models.py, src/api/routes.py, src/front/js/component/BusinessOfferCard.jsx, src/front/js/component/FavoriteOffer.jsx, src/front/js/component/FavoriteReview.js, src/front/js/component/HomeReviewCard.jsx, src/front/js/component/MyReviews.js, src/front/js/component/Navbar.jsx, src/front/js/component/OffersDoubleModal.jsx, src/front/js/component/ReviewsDoubleModal.jsx, src/front/js/pages/Reviews.js, src/front/js/pages/SingleOfferView.jsx, src/front/js/pages/SingleReviewView.jsx, src/front/styles/card-review.css, src/front/styles/homeOfferCard.css, src/front/styles/homeReviewCard.css, src/front/styles/index.css, src/front/styles/singlereview.css
=> review from offer OK

src/api/models.py, src/api/routes.py, src/front/js/component/AllFavoritesOffers.js, src/front/js/component/BusinessOfferCard.jsx, src/front/js/component/DonationForm.js, src/front/js/component/HomeOfferCard.jsx, src/front/js/component/MyOffers.jsx, src/front/js/component/OffersDoubleModal.jsx, src/front/js/component/ReviewsDoubleModal.jsx, src/front/js/pages/SingleOfferView.jsx, src/front/styles/generalInfoDiv.css, src/front/styles/homeOfferCard.css, src/front/styles/homeReviewCard.css, src/front/styles/navbar.css, src/front/styles/reviewsDoubleModal.css
=> styles and some stuff

package-lock.json, package.json, src/front/js/component/Navbar.jsx, src/front/js/component/OffersDoubleModal.jsx, src/front/js/component/PayPalCheckoutButton.js, src/front/js/component/ReviewsDoubleModal.jsx, src/front/js/component/SignUpBusiness.js, src/front/js/component/SignUpUser.jsx, src/front/js/pages/LogIn.jsx
=> sweet alert OK

src/api/routes.py, src/front/js/component/HomeOfferCard.jsx, src/front/js/component/HomeReviewCard.jsx, src/front/js/component/ReviewsDoubleModal.jsx, src/front/js/pages/SingleOfferView.jsx
Link between  offers and reviews, some styles
=> Link between  offers and reviews, some styles
